#!/usr/bin/env node
// Generates STATUS.md and STATUS.json — the single source of truth for build/test status.
//
// This script is run LAST by `npm run verify`, so it only executes when the
// entire gate (build + tests + 4 smokes + npm audit) has already passed. That
// means STATUS always reflects a known-green tree. It can also be run standalone
// via `npm run status` (it then reports whatever the last `test:ci` produced).
//
// Do NOT hand-edit STATUS.md / STATUS.json, and do NOT copy these counts into
// narrative docs — link to STATUS instead. This structurally prevents the
// "N files / M tests" snapshots from drifting out of sync.

import { readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";

const root = process.cwd();

function readJSON(path, fallback = null) {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return fallback;
  }
}

function git(cmd, fallback = "") {
  try {
    return execSync(`git ${cmd}`, { encoding: "utf8" }).trim();
  } catch {
    return fallback;
  }
}

const pkg = readJSON(`${root}/package.json`, {});
const vitest = readJSON(`${root}/.status/vitest-result.json`);
const coverageSummary = readJSON(`${root}/coverage/coverage-summary.json`);

const branch = git("rev-parse --abbrev-ref HEAD", "unknown");
const sha = git("rev-parse --short HEAD", "unknown");
// Count working-tree changes, excluding the status outputs this script writes
// (otherwise a freshly-verified clean tree would always report itself dirty).
const dirtyCount = git("status --porcelain", "")
  .split("\n")
  .filter((line) => line.length > 0)
  .map((line) => line.slice(3).replace(/^"|"$/g, ""))
  .filter((path) => path && path !== "STATUS.md" && path !== "STATUS.json" && path !== "SCORECARD.md" && path !== "SCORECARD.json" && !path.startsWith(".status/")).length;

let files = null;
let tests = null;
let passed = null;
let failed = null;
let testSuccess = null;
if (vitest) {
  // `testResults` has one entry per test FILE; `numTotalTestSuites` counts
  // suite blocks (files + describes) and would over-report the file count.
  files = Array.isArray(vitest.testResults) ? vitest.testResults.length : (vitest.numTotalTestSuites ?? null);
  tests = vitest.numTotalTests ?? null;
  passed = vitest.numPassedTests ?? null;
  failed = vitest.numFailedTests ?? null;
  testSuccess = vitest.success ?? failed === 0;
}

let coverage = null;
if (coverageSummary?.total) {
  const total = coverageSummary.total;
  coverage = {
    lines: total.lines?.pct ?? null,
    statements: total.statements?.pct ?? null,
    functions: total.functions?.pct ?? null,
    branches: total.branches?.pct ?? null
  };
}

const generatedAt = new Date().toISOString();

const status = {
  package: pkg.name ?? "browser-agent-mcp-farm",
  version: pkg.version ?? "unknown",
  branch,
  commit: sha,
  workingTree: dirtyCount === 0 ? "clean" : `dirty (${dirtyCount} files)`,
  generatedAt,
  gate: "npm run verify",
  verify: "PASS",
  tests: { files, tests, passed, failed, success: testSuccess },
  coverage,
  note: "Generated by `npm run verify`. Single source of truth for build/test status. Do not hand-edit; do not copy counts into narrative docs."
};

writeFileSync(`${root}/STATUS.json`, `${JSON.stringify(status, null, 2)}\n`);

const md = `# Project Status

> Generated by \`npm run verify\` — **do not hand-edit**. This file is the single
> source of truth for build/test status. Do not copy these numbers into narrative
> docs (AGENTS.md, NEXT_TASKS.md, DEVELOPMENT_HISTORY.md); link here instead.

| Field | Value |
| --- | --- |
| Package | \`${status.package}\` v${status.version} |
| Branch | \`${branch}\` |
| Commit | \`${sha}\` |
| Working tree | ${status.workingTree} |
| Generated | ${generatedAt} |
| Verify gate | **${status.verify}** (build + tests + 4 smokes + npm audit) |
| Tests | ${tests ?? "?"} tests in ${files ?? "?"} files (${passed ?? "?"} passed, ${failed ?? 0} failed) |
| Coverage | ${coverage ? `lines ${coverage.lines}% · statements ${coverage.statements}% · functions ${coverage.functions}% · branches ${coverage.branches}% (ratcheting floor toward 80%)` : "not measured this run"} |

The verify gate is:
\`npm run build && npm run test:ci && smoke + smoke:web + smoke:media + smoke:proxy && npm audit && npm run status\`.
\`npm run status\` runs last, so STATUS only updates when the entire gate is green.
`;
writeFileSync(`${root}/STATUS.md`, md);

console.log(`STATUS written: v${status.version} ${sha} — ${tests ?? "?"} tests / ${files ?? "?"} files, verify PASS`);
